字符串处理拓展
CCW-Site/ccw-user-extension pull request #106
Opened 2023-08-22 12:49 UTC by qxsck

收录一些处理字符串的方法的拓展

2023-08-22 14:18 UTC, 10-cookies commented
你的字符串处理能不能加一个重复字符串多少多少次的积木

2023-08-23 09:40 UTC, qxsck commented
> 你的字符串处理能不能加一个重复字符串多少多少次的积木

今天更新，我会尝试增加一些东西

2023-08-23 09:42 UTC, qxsck commented
> 你的字符串处理能不能加一个重复字符串多少多少次的积木

位运算的文件我删掉了

2023-08-24 06:38 UTC, 10-cookies commented
> > 你的字符串处理能不能加一个重复字符串多少多少次的积木
> 
> 位运算的文件我删掉了

好

2023-08-28 07:47 UTC, sylarhcn requested changes
缺少积木的英文翻译。
如何翻译可以参考其他已上线的扩展代码

2023-08-28 09:02 UTC, qxsck commented
> 缺少积木的英文翻译。 如何翻译可以参考其他已上线的扩展代码

加了加了，现在可以了吗

2023-08-30 10:11 UTC, sylarhcn approved these changes

2023-08-30 10:12 UTC, merged