Emojis
CCW-Site/ccw-user-extension pull request #178
Opened 2024-02-05 21:52 UTC by DilemmaGX

### Get and parse emojis.
Also included some new ~~and fancy~~ stuff (Animated PNG Icons).

Still experimenting with tooltips (title), but not implemented in this version.

### Reference(s):
|Fragment|Related Source|
|------|------|
|`emoji json`|https://unpkg.com/@angelofana/emoji-json@15.1.1/emoji-array.json|
|`grinning cat (3D)`|https://github.com/microsoft/fluentui-emoji|
|`animated grinning cat (3D)`|https://github.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis|

2024-02-05 22:06 UTC, DilemmaGX commented
![image](https://github.com/Gandi-IDE/custom-extension/assets/111679857/3a62bd2c-37ea-4d7b-9c31-1381b574449f)

https://github.com/Gandi-IDE/custom-extension/assets/111679857/dfa88237-61dd-48bf-9aed-f27b5cd7e8b2

2024-02-06 01:17 UTC, fath11 commented
Oh god...

I would recommend you use this package: https://www.npmjs.com/package/emoji-dictionary
Also, I don't know the point of `get all data` block as it is VERY laggy on my computer.

2024-02-06 03:33 UTC, DilemmaGX commented
> Oh god...
> 
> I would recommend you use this package: https://www.npmjs.com/package/emoji-dictionary Also, I don't know the point of `get all data` block as it is VERY laggy on my computer.

Thanks for your advice. the `get all data` block is opened to users to recreate some of their own emoji functions and data type.

**About lag issues**: Well, II believed that the lag caused by `get all data` is mainly due to Gandi's scratch-gui, when trying to draw tremendous amount of text inside the reporter return box (or the variable monitors). In real projects, programmers were expected to create programmes using data returned by `get all data` instead of directly monitoring it. In my test, avoiding directly rendering the return value on screen (eg: use it with Not.js or other json processors) will not cause lags

2024-05-11 11:44 UTC, DilemmaGX commented
Used unpkg as data source (instead of embeding inside the project)

2024-05-21 01:47 UTC, sylarhcn requested changes
1. 封面过大，请不要将过大的文件数据 base64 到扩展实现文件中，封面仅用于目录展示，你可以使用 module 分隔
2. 封面尺寸和大小有标准，请参看 readme 中的 asset 标准，理论上封面越小越好，可以加快目录的展示速度
3. 单个文件过大，在 github 网页 pr 的 file changed 中 ，无法展示 diff，reviewer 无法查看。

2024-07-23 02:46 UTC, DilemmaGX commented
Mark as on hold. Will be reworking after a couple of time.

2025-12-31 04:07 UTC, closed without merging