Threejs-CCW
CCW-Site/ccw-user-extension pull request #207
Opened 2024-03-23 13:29 UTC by xiaochen004hao

# **共创世界-3D扩展！**
## ThreejsCCW.js为主文件
### 可将ThreejsCCW.js根目录下的其他文件放在CCW cdn，在ThreejsCCW.js的开头处替换导入的路径

### [示例demo](https://www.ccw.site/gandi/project/65fecfcfdf30e51731df0e25)
---

##### _PR一定要过啊！！！这个扩展我付出了很多心血（因为不可描述的原因，我只能周六上线）_
# 🫶🫶🫶

2024-03-23 13:32 UTC, xiaochen004hao commented
# **HCN可以把这个扩展放到”开发中的扩展“**

2024-03-23 14:41 UTC, Nightre commented on ThreejsCCW/ThreejsCCW.js
> +        this._ccw = document.getElementsByClassName('gandi_stage_stage_1fD7k')[0].getElementsByTagName("canvas")[0];
可以用 runtime.renderer.canvas

2024-03-24 06:50 UTC, fath11 commented
1. You should make the custom canvas automatically resize, look at BBCode's source
2. The demo project isn't shared? its says no access and i cant get the extension to work 
![image](https://github.com/Gandi-IDE/custom-extension/assets/124476952/3bec816c-f0aa-4b3d-9fbe-192c0bf6e7de)

2024-03-24 09:58 UTC, fath11 commented
What I am worrying about is support for Quake and GKamera. Looking at how the extension works, GKamera won't be a problem, but the Quake extension might be a different story.

Maybe this extension might need its own "load shader" block. If you look at #204 it's possible to get files from the Code Editor. Since i myself have been experimenting with Three.js for the past 3 months, i can create this feature if i have the time but don't expect me to work on it. Tho it will be great if you can

2024-03-24 12:07 UTC, FurryR commented on ThreejsCCW/ThreejsCCW.js
> +import {OBJLoader} from "https://livefile.xesimg.com/programme/python_assets/5bcc04d1d301d7a3e096fa6b8708af7f.js";
先有学而思后有天。请勿使用学而思临时文件。可以参考 lpp 那样，配置一个脚手架/打包器。

2024-03-24 12:08 UTC, FurryR commented on ThreejsCCW/ThreejsCCW.js
> +console.log(THREE);
```suggestion
```

调试信息不应当出现在送审的版本。

2024-03-24 12:09 UTC, FurryR commented on ThreejsCCW/ThreejsCCW.js
> +        this.lights = new Object();
```suggestion
        this.lights = {};
```

2024-03-24 12:11 UTC, FurryR commented on ThreejsCCW/ThreejsCCW.js
> +        if (document.getElementsByClassName('gandi_stage_stage_1fD7k')[0].getElementsByClassName("ThreejsCCW").length == 0) {
硬编码这种带随机数的 id 会在下一次更新时立即失效。考虑改用 runtime.renderer.canvas。

2024-03-24 12:11 UTC, FurryR commented on ThreejsCCW/ThreejsCCW.js
> +        // this._ccw.style.display = "none";  // 隐藏原CCW显示canvas
为什么不能原版和 ThreeJS 共存呢？

2024-03-24 12:13 UTC, FurryR requested changes
勇气可嘉，技术太菜。隔壁我记得有人做过兼容 Scratch 原版的 Three 了。

2024-03-24 12:33 UTC, xiaochen004hao commented
我只能周六用电脑。。。

在 2024-03-24 20:08:54，"凌" ***@***.***> 写道：


@FurryR commented on this pull request.

In ThreejsCCW/ThreejsCCW.js:

> @@ -0,0 +1,1288 @@
+// 依赖库
+import * as THREE from ***@***.***/build/three.module.js";
+
+// 插件
+// 这里为该扩展目录下的三个js文件
+import {OBJLoader} from "https://livefile.xesimg.com/programme/python_assets/5bcc04d1d301d7a3e096fa6b8708af7f.js";
+import {OrbitControls} from 'https://livefile.xesimg.com/programme/python_assets/22b053c1486c0311a7e493e9419cebf7.js';
+import {MTLLoader} from 'https://livefile.xesimg.com/programme/python_assets/bfdf94e29d1b77c18dbfc5aa778e6df7.js';
+// import {OBJLoader} from ***@***.***/file/OBJLoader.js";
+// import {OrbitControls} from ***@***.***/file/OrbitControls.js';
+// import {MTLLoader} from ***@***.***/file/MTLLoader.js';
+import WebGL from ***@***.***/examples/jsm/capabilities/WebGL.js';
+
+console.log(THREE);

⬇️ Suggested change
-console.log(THREE);


调试信息不应当出现在送审的版本。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-03-24 12:38 UTC, xiaochen004hao commented
To be frank, who are you? I can only use the computer on Saturdays... Strive to revise all the suggestions completely

在 2024-03-24 17:59:02，fath11 ***@***.***> 写道：


What I am worrying about is support for Quake and GKamera. Looking at how the extension works, GKamera won't be a problem, but the Quake extension might be a different story.

Maybe this extension might need its own "load shader" block. If you look at #204 it's possible to get files from the Code Editor. Since i myself have been experimenting with Three.js for the past 3 months, i can create this feature if i have the time but don't expect me to work on it. Tho it will be great if you can

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-03-24 12:39 UTC, xiaochen004hao commented
因为我js dom很菜，菜就多练的那种

在 2024-03-24 20:12:10，"凌" ***@***.***> 写道：


@FurryR commented on this pull request.

In ThreejsCCW/ThreejsCCW.js:

> +            })
+        }
+     
+        this.scene.remove(model);
+
+    }
+
+    /**
+     * 初始化
+     * @param {number} args.color
+     * @param {number} args.sizey
+     * @param {number} args.sizex
+     * @param {string} args.Anti_Aliasing
+     */
+    init(args) {
+        // this._ccw.style.display = "none";  // 隐藏原CCW显示canvas


为什么不能原版和 ThreeJS 共存呢？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-03-24 12:42 UTC, xiaochen004hao commented
那么，objects是不是也得这样搞

在 2024-03-24 20:09:39，"凌" ***@***.***> 写道：


@FurryR commented on this pull request.

In ThreejsCCW/ThreejsCCW.js:

> +        // 场景
+        this.scene = null;
+
+        // 相机配置
+        this.fov = null;
+        this.aspect = null;
+        this.near = null;
+        this.far = null;
+        this.camera = null;
+        this.controls = null;
+
+        // 环境光
+        this.ambient_light = null;
+
+        // 光
+        this.lights = new Object();

⬇️ Suggested change
-        this.lights = new Object();
+        this.lights = {};


—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-03-24 12:58 UTC, xiaochen004hao commented
> 勇气可嘉，技术太菜。隔壁我记得有人做过兼容 Scratch 原版的 Three 了。

神奇，在github发的评论在我的网易邮箱写能看到唉

2024-03-24 13:00 UTC, fath11 commented
> 勇气可嘉，技术太菜。隔壁我记得有人做过兼容 Scratch 原版的 Three 了。Courage is commendable, and technology is too good. Next door I remember someone making a Three that was compatible with the original Scratch version.

The extension uses skins. I am also trying to make a 3D extension that will coexist with Scratch without the use of skins but it requires me to learn more about WebGL which is very time-consuming as I have 0 prior knowledge about it. I am getting closer tho, the only thing slowing me down is school.

I am actually surprised someone made this PR.

2024-03-24 13:08 UTC, xiaochen004hao commented
> 1. You should make the custom canvas automatically resize, look at BBCode's source
> 2. The demo project isn't shared? its says no access and i cant get the extension to work
>    ![image](https://private-user-images.githubusercontent.com/124476952/316290444-3bec816c-f0aa-4b3d-9fbe-192c0bf6e7de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODU5MTcsIm5iZiI6MTcxMTI4NTYxNywicGF0aCI6Ii8xMjQ0NzY5NTIvMzE2MjkwNDQ0LTNiZWM4MTZjLWYwYWEtNGIzZC05ZmJlLTE5MmMwYmY2ZTdkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxMzA2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmU0MWMxOWI4NTllZGRiMzkyMmRhNDVmNmE4NzFhM2JkNTc5Yjg2ZDA4NTZlYTkwOTViOGJhMzllOWQ0NzNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v-hnKLM4TJqU2jqfgDKSkkk71Z_7jvUpBAlLLlFg5iY)
> 3. Perhaps you should consider changing the extension's name to avoid confusion with Three

可是，装了自定义扩展的作品发不出来，难道我要发观察者邀请链接（应该是的）

2024-03-24 13:10 UTC, xiaochen004hao commented
> 勇气可嘉，技术太菜。隔壁我记得有人做过兼容 Scratch 原版的 Three 了。
还要，我几乎没学过js，当c++ + Python来写的🙂

2024-03-24 13:10 UTC, kukemc commented
> > 1. 您应该让自定义画布自动调整大小，查看 BBCode 的源代码
> > 2. 演示项目没有共享？它说没有访问权限，我无法让扩展程序工作
> >    ![image](https://private-user-images.githubusercontent.com/124476952/316290444-3bec816c-f0aa-4b3d-9fbe-192c0bf6e7de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODU5MTcsIm5iZiI6MTcxMTI4NTYxNywicGF0aCI6Ii8xMjQ0NzY5NTIvMzE2MjkwNDQ0LTNiZWM4MTZjLWYwYWEtNGIzZC05ZmJlLTE5MmMwYmY2ZTdkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxMzA2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmU0MWMxOWI4NTllZGRiMzkyMmRhNDVmNmE4NzFhM2JkNTc5Yjg2ZDA4NTZlYTkwOTViOGJhMzllOWQ0NzNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v-hnKLM4TJqU2jqfgDKSkkk71Z_7jvUpBAlLLlFg5iY)
> > 3. 也许您应该考虑更改扩展名以避免与 Three 混淆
> 
> 可是，装了自定义扩展的作品发不出来，难道我要发观察者邀请链接（应该是的）

你应该将扩展挂到cdn上然后直接发链接

2024-03-24 13:11 UTC, xiaochen004hao commented
> > > 1. 您应该让自定义画布自动调整大小，查看 BBCode 的源代码
> > > 2. 演示项目没有共享？它说没有访问权限，我无法让扩展程序工作
> > >    ![image](https://private-user-images.githubusercontent.com/124476952/316290444-3bec816c-f0aa-4b3d-9fbe-192c0bf6e7de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODU5MTcsIm5iZiI6MTcxMTI4NTYxNywicGF0aCI6Ii8xMjQ0NzY5NTIvMzE2MjkwNDQ0LTNiZWM4MTZjLWYwYWEtNGIzZC05ZmJlLTE5MmMwYmY2ZTdkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxMzA2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmU0MWMxOWI4NTllZGRiMzkyMmRhNDVmNmE4NzFhM2JkNTc5Yjg2ZDA4NTZlYTkwOTViOGJhMzllOWQ0NzNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v-hnKLM4TJqU2jqfgDKSkkk71Z_7jvUpBAlLLlFg5iY)
> > > 3. 也许您应该考虑更改扩展名以避免与 Three 混淆
> > 
> > 
> > 可是，装了自定义扩展的作品发不出来，难道我要发观察者邀请链接（应该是的）
> 
> 你应该将扩展挂到cdn上然后直接发链接

你是，酷可！

2024-03-24 13:12 UTC, xiaochen004hao commented
> > > 1. 您应该让自定义画布自动调整大小，查看 BBCode 的源代码
> > > 2. 演示项目没有共享？它说没有访问权限，我无法让扩展程序工作
> > >    ![image](https://private-user-images.githubusercontent.com/124476952/316290444-3bec816c-f0aa-4b3d-9fbe-192c0bf6e7de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODU5MTcsIm5iZiI6MTcxMTI4NTYxNywicGF0aCI6Ii8xMjQ0NzY5NTIvMzE2MjkwNDQ0LTNiZWM4MTZjLWYwYWEtNGIzZC05ZmJlLTE5MmMwYmY2ZTdkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxMzA2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmU0MWMxOWI4NTllZGRiMzkyMmRhNDVmNmE4NzFhM2JkNTc5Yjg2ZDA4NTZlYTkwOTViOGJhMzllOWQ0NzNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v-hnKLM4TJqU2jqfgDKSkkk71Z_7jvUpBAlLLlFg5iY)
> > > 3. 也许您应该考虑更改扩展名以避免与 Three 混淆
> > 
> > 
> > 可是，装了自定义扩展的作品发不出来，难道我要发观察者邀请链接（应该是的）
> 
> 你应该将扩展挂到cdn上然后直接发扩展url

还有

2024-03-24 13:12 UTC, closed without merging

2024-03-24 13:13 UTC, xiaochen004hao commented
> > > 1. 您应该让自定义画布自动调整大小，查看 BBCode 的源代码
> > > 2. 演示项目没有共享？它说没有访问权限，我无法让扩展程序工作
> > >    ![image](https://private-user-images.githubusercontent.com/124476952/316290444-3bec816c-f0aa-4b3d-9fbe-192c0bf6e7de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODU5MTcsIm5iZiI6MTcxMTI4NTYxNywicGF0aCI6Ii8xMjQ0NzY5NTIvMzE2MjkwNDQ0LTNiZWM4MTZjLWYwYWEtNGIzZC05ZmJlLTE5MmMwYmY2ZTdkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxMzA2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmU0MWMxOWI4NTllZGRiMzkyMmRhNDVmNmE4NzFhM2JkNTc5Yjg2ZDA4NTZlYTkwOTViOGJhMzllOWQ0NzNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v-hnKLM4TJqU2jqfgDKSkkk71Z_7jvUpBAlLLlFg5iY)
> > > 3. 也许您应该考虑更改扩展名以避免与 Three 混淆
> > 
> > 
> > 可是，装了自定义扩展的作品发不出来，难道我要发观察者邀请链接（应该是的）
> 
> 你应该将扩展挂到cdn上然后直接发扩展url

唉 我刚才按了什么

2024-03-27 10:34 UTC, MoreBugOfDog commented
> > > > 1. 您应该让自定义画布自动调整大小，查看 BBCode 的源代码
> > > > 2. 演示项目没有共享？它说没有访问权限，我无法让扩展程序工作
> > > >    ![图像](https://private-user-images.githubusercontent.com/124476952/316290444-3bec816c-f0aa-4b3d-9fbe-192c0bf6e7de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODU5MTcsIm5iZiI6MTcxMTI4NTYxNywicGF0aCI6Ii8xMjQ0NzY5NTIvMzE2MjkwNDQ0LTNiZWM4MTZjLWYwYWEtNGIzZC05ZmJlLTE5MmMwYmY2ZTdkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxMzA2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmU0MWMxOWI4NTllZGRiMzkyMmRhNDVmNmE4NzFhM2JkNTc5Yjg2ZDA4NTZlYTkwOTViOGJhMzllOWQ0NzNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v-hnKLM4TJqU2jqfgDKSkkk71Z_7jvUpBAlLLlFg5iY)
> > > > 3. 也许您应该考虑更改扩展名以避免与 Three 混淆
> > > 
> > > 
> > > 可是，装了自定义扩展的作品发不出来，难道我要发观察者邀请链接（应该是的）
> > 
> > 
> > 你应该将扩展挂到cdn上，然后直接发扩展url
> 
> 唉 我刚才按了什么

你**关闭**了这个PR，也就是说你取消了审核。。
如果需要审核，请**再次发起PR**

2025-11-22 21:05 UTC, xiaochen004hao commented
考古，其实这里也是我第一次使用Github的地方

2025-12-02 14:01 UTC, hwxqyworld commented on ThreejsCCW/ThreejsCCW.js
> +import {OBJLoader} from "https://livefile.xesimg.com/programme/python_assets/5bcc04d1d301d7a3e096fa6b8708af7f.js";
> 先有学而思后有天。不要使用学而思临时文件。可以参考lpp那样，配置一个脚手架/备份器。

捉