feat: created BetterEvents.js
CCW-Site/ccw-user-extension pull request #235
Opened 2024-04-28 19:16 UTC by sil3nt884

- added events to allow paylaods.

2024-04-29 07:12 UTC, fath11 commented
I recommend following this https://github.com/FurryR/wheeling/blob/main/doc/en-us/getting-started/compatibility.md if you want to keep compatibility with other Scratch mods.

2024-04-29 08:24 UTC, little-starts commented
Gandi already has an extension of this feature.

2024-05-11 10:29 UTC, sylarhcn reviewed
1. Could you add Chinese translation?(Optional)
2. There has a similar extension named "4D pocket" in Gandi, you can check it first
3. If you still want to merge after you read it, I'll merge it

2024-06-05 13:23 UTC, MoreBugOfDog requested changes

2024-06-05 13:23 UTC, MoreBugOfDog commented on silentsoul884/BetterEvents.js
> +    })(Scratch);
Gandi-IDE has opened vm to all extensions, this method used to differentiate between Turbowarp and Gandi-IDE is not working. This method of distinguishing between Turbowarp and Gandi-IDE does not work, and may result in missing registration information in Gandi.

2024-06-05 13:25 UTC, MoreBugOfDog commented
> 1. Could you add Chinese translation?(Optional)
> 2. There has a similar extension named "4D pocket" in Gandi, you can check it first
> 3. If you still want to merge after you read it, I'll merge it

Is Chinese translation optional in Gandi-IDE? The majority of Gandi-IDE users are from China! It is recommended to raise the threshold for expanding translations. (No nationality or racial discrimination here, just a suggestion on the way of operation)

2026-07-05 14:55 UTC, closed without merging