创建：WindowRig
CCW-Site/ccw-user-extension pull request #253
Opened 2024-05-26 09:41 UTC by MoreBugOfDog

// Name: Skydog's WindowRig
// Version: 1.0.0
// ID: WindowRig
// Description: Manipulate the window object! Set the page icon！
// By: MoreBugOfDog
// License: MPL-2.0
// 本拓展经过开发者严格的法律审查，不涉及任何违法行为。
// 使用本拓展造成的任何后果与开发者无关。
// ——————不重要的——————————
// 解释一下拓展id为什么用的是rig（直译：装置）而不是操纵：
// 因为操纵的英语太长了，不便于直接书写，所以用rig来代替。

这个拓展，可以实现对浏览器页面的操纵。
包括滚动页面、修改网页ico（即图标）、修改网页title（标题）等功能
满足了 @fath11 提的需求。
主要通过window对象实现。

2024-05-31 06:32 UTC, kukemc commented
感觉更应该是给系统工具提pr 而不是单独一个扩展

2024-05-31 10:40 UTC, qxsck commented
适合加入系统工具

2024-06-03 11:36 UTC, MoreBugOfDog commented
> 适合加入系统工具

在main分支中，我没找到系统工具的源码 @sylarhcn @yuen619

2024-06-03 13:08 UTC, kukemc commented
> > 适合加入系统工具
> 
> 在main分支中，我没找到系统工具的源码 @sylarhcn @yuen619

系统工具不在main分支里面在developer分支里

2024-06-12 06:34 UTC, sylarhcn requested changes

2024-06-12 06:35 UTC, sylarhcn requested changes

2024-06-12 06:35 UTC, sylarhcn commented on .gitignore
请不要修改 gitignore 文件

2025-08-30 06:58 UTC, closed without merging