scratch高级模块提交
CCW-Site/ccw-user-extension pull request #26
Opened 2022-10-01 10:41 UTC by DannyDevPro

目前实现ws，http，baseXX加密 json（通过id操作，也就是说，其他目前上线的扩展只支持同时操作一个，而这个可以操作多个）
目前http有跨域现象，预计在下一个版本对接好我编写的auroralink （https://gitee.com/ausx/aurora-link-for-sc）就可以通过python发送请求，避免跨域，还有就是对接了后可以实现TCP/UDP

2022-10-08 03:02 UTC, sylarhcn commented
有一个小小的担忧，如果在 ccw 开放这种积木，会不会很容易被人当成 ddos 的工具使用。

2022-10-08 10:31 UTC, sylarhcn requested changes

2022-10-08 10:31 UTC, sylarhcn commented on dannydev/scCOM.js
> +class AuEx_communication {
class name 请使用大驼峰

2022-10-08 10:31 UTC, sylarhcn commented on dannydev/scCOM.js
> +module.exports = AuEx_communication;
你看看 template 呢，你没有将扩展注册到window的临时变量上，是没有办法成功加载的在测试环境下

2022-10-08 10:31 UTC, sylarhcn commented on dannydev/scCOM.js
> +                'AusCOM.extensionName': 'AUSの通讯模块',
总感觉 AusCom 这个 namespace 很容易被重名啊。这个改不改看你

2022-10-08 10:31 UTC, sylarhcn commented on dannydev/scCOM.js
> +                'AusCOM.extensionName': 'AUSの通讯模块',
建议可以使用 CCW 用户名+扩展名来做 namespace 比如用户名（WitCat）扩展名（FileHelper）- WitCatFileHelper

2022-10-08 10:31 UTC, sylarhcn commented on dannydev/scCOM.js
> +            id: 'AUdevNet', // 拓展id
建议拓展id 与上面的说的 namespace 用同样的字符串

2022-10-08 10:31 UTC, sylarhcn commented on dannydev/scCOM.js
> +        else{return this.httpGet(site+get_p(p), body, g_way);}
代码格式问题

2022-10-08 10:31 UTC, sylarhcn commented on dannydev/scCOM.js
> +        else{return this.httpGet(site+get_p(p), body, g_way);}
建议使用格式化插架美化一下。任何标准配置都可以

2022-10-08 10:31 UTC, sylarhcn commented on dannydev/scCOM.js
> +        return "http访问出现fail to load XX可能是域名/ip不存在，也有可能是出现跨域问题，可以联系本站站住修改HTTP协议头或者自行修改浏览器跨域设置。如果ws无法发送数据，请F12打开开发者工具查看是否报错，如果报错则是无法连接，目前浏览器还不支持侦察此类报错。更多帮助请进入 https://gitee.com/ausx/scCOM"
翻译

2022-10-12 14:26 UTC, pwned4ever2 commented
我是Senpai，这个链接udp和tcp应该问题不大。写这个模块的时候可以限制流量吧？我原来研究过一点ddos技术（僵尸网络，别来抓我）
主要是看西瓜的服务器怎么样。且西瓜服务器的保护一般tcpudp打不破的，主要看他是不是有bypass或者很大流量。有tcp和udp模块无伤大雅，还可以连api等。用西瓜的scratch平台不好做ddos工具，这个是可以放心的。希望能加tcp udp
———Senpai，极光工作室高管

2022-10-15 15:29 UTC, merged

2022-10-16 12:42 UTC, sylarhcn commented on dannydev/scCOM.js
> +      iconURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAAB2CAYAAACNmNybAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAACxIAAAsSAdLdfvwAAKMNSURBVHhepf0HtG5bdtcHri+d76Sb7333xXqVXimBAhKUc
1. 格式错误， 少逗号
2. 这里请使用图片文件并 import 方式引入。

不要直接复制 base64 数据。不可读，不可维护。。。

你可以看example 的写法。